# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainViayou', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travels',
            options={'ordering': ['date'], 'verbose_name': 'Travel', 'verbose_name_plural': 'Travels'},
        ),
        migrations.AlterField(
            model_name='travels',
            name='grade',
            field=models.CharField(blank=True, help_text='Evaluation for the travel', max_length=50, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='origin_code',
            field=models.CharField(help_text='The origin of the travel, city code is saved', max_length=50, verbose_name='Origin'),
        ),
    ]
