# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainViayou', '0003_auto_20160308_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='destination_code',
            field=models.IntegerField(help_text='The destination of the travel, city code is saved', max_length=20, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Evaluation for the travel', null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='origin_code',
            field=models.CharField(help_text='The origin of the travel, city code is saved', max_length=20, verbose_name='Origin'),
        ),
    ]
