# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainViayou', '0004_auto_20160308_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='destination_code',
            field=models.CharField(help_text='The destination of the travel, city code is saved', max_length=20, verbose_name='Destination'),
        ),
    ]
