# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 04:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainViayou', '0005_auto_20160308_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='destination_code',
            field=models.CharField(help_text='The destination of the travel, city code is saved', max_length=10, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Evaluation for the travel', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='origin_code',
            field=models.CharField(help_text='The origin of the travel, city code is saved', max_length=10, verbose_name='Origin'),
        ),
    ]
