# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 04:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainViayou', '0006_auto_20160308_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travels', models.ManyToManyField(related_name='categories', to='MainViayou.Travels', verbose_name='Travels')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoriesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='Name of the category', max_length=200, verbose_name='Name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='MainViayou.Categories')),
            ],
            options={
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'MainViayou_categories_translation',
                'verbose_name': 'Category Translation',
            },
        ),
        migrations.CreateModel(
            name='ContainedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Min')),
                ('max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max')),
                ('measure', models.CharField(choices=[('m', 'M'), ('dm', 'Dm'), ('cm', 'Cm'), ('mm', 'Mm')], max_length=3, verbose_name='Measure')),
            ],
            options={
                'verbose_name': 'ContainedIn',
                'verbose_name_plural': 'ContainedIn',
            },
        ),
        migrations.AlterField(
            model_name='keywordtranslation',
            name='keywords',
            field=models.CharField(blank=True, help_text='keywords split by ,', max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriestranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
